TukuiL = { }

-- update needed msg
TukuiL.option_update = "You need to update your Tukui ConfigUI addon because of Tukui latest changes, please visit www.tukui.org"

-- general
TukuiL.option_general = "General"
TukuiL.option_general_uiscale = "Auto UI Scale"
TukuiL.option_general_override = "Use High resolution  layout on a Lower resolution"
TukuiL.option_general_overridelow = "Use Low resolution  layout on a Higher resolution"
TukuiL.option_general_multisample = "Multisampling protection (clean 1px border)"
TukuiL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"
TukuiL.option_general_classcolor = "Class Color Theme"
TukuiL.option_general_backdropcolor = "Set default backdrop color of panels"
TukuiL.option_general_bordercolor = "Set default border color of panels"
TukuiL.option_general_blizzardreskin = "Reskin Blizzard frames to match Tukui"

-- media
TukuiL.option_media = "Media"
TukuiL.option_media_font = "Set general font of tukui"
TukuiL.option_media_uffont = "Set general font of unitframes"
TukuiL.option_media_dmgfont = "Set general font of dmg / sct"
TukuiL.option_media_npfont = "Set general font of nameplates"
TukuiL.option_media_pixelfont = "Set pixel font of tukui"
TukuiL.option_media_normTex = "Set texture used for tukui healthbar/powerbar/etc"
TukuiL.option_media_glowTex = "Set the glow text around some frame"
TukuiL.option_media_bubbleTex = "Set unitframes combo points"
TukuiL.option_media_copyicon = "Set copy icon"
TukuiL.option_media_configicon = "Set config icon"
TukuiL.option_media_blank = "Set the main texture for all borders/panels"
TukuiL.option_media_bordercolor = "Set border color of tukui panels"
TukuiL.option_media_altbordercolor = "Set alternative border color, mainly for unitframes text panels"
TukuiL.option_media_backdropcolor = "Set background color of tukui panels"
TukuiL.option_media_buttonhover = "Set buttonhover texture"
TukuiL.option_media_whisper = "Set whisper sound"
TukuiL.option_media_warning = "Set warning sound"

-- nameplate
TukuiL.option_nameplates = "Nameplates"
TukuiL.option_nameplates_enable = "Enable Nameplates"
TukuiL.option_nameplates_enhancethreat = "Enable threat feature, automatically changes by your role"
TukuiL.option_nameplates_showhealth = "Show health on nameplate"
TukuiL.option_nameplates_combat = "Only show enemy nameplates in-combat"
TukuiL.option_nameplates_goodcolor = "Good threat color, varies depending if your a tank or dps/heal"
TukuiL.option_nameplates_badcolor = "Bad threat color, varies depending if your a tank or dps/heal"
TukuiL.option_nameplates_transitioncolor = "Losing/Gaining threat color"

-- merchant
TukuiL.option_merchant = "Merchant"
TukuiL.option_merchant_autosell = "Auto sell grey items"
TukuiL.option_merchant_autorepair = "Auto Repair items"
TukuiL.option_merchant_sellmisc = "Sell some defined (craps not grey) items automatically"

-- bags
TukuiL.option_bags = "Bags"
TukuiL.option_bags_enable = "Enable all-in-one bag"

-- datatext
TukuiL.option_datatext = "Data Text"
TukuiL.option_datatext_24h = "Enable 24h time"
TukuiL.option_datatext_localtime = "Use Local Time instead of Server Time"
TukuiL.option_datatext_bg = "Enable Battleground Stats"
TukuiL.option_datatext_hps = "Healing per second, position (0 for disabled)"
TukuiL.option_datatext_guild = "Guild position (0 for disabled)"
TukuiL.option_datatext_mem = "Memory position (0 for disabled)"
TukuiL.option_datatext_bags = "Bags position (0 for disabled)"
TukuiL.option_datatext_fontsize = "Font size of text"
TukuiL.option_datatext_fps_ms = "Latency and FPS position (0 for disabled)"
TukuiL.option_datatext_armor = "Armor Position (0 for disabled)"
TukuiL.option_datatext_avd = "Avoidance position (0 for disabled)"
TukuiL.option_datatext_power = "Power position (0 for disabled)"
TukuiL.option_datatext_haste = "Haste position (0 for disabled)"
TukuiL.option_datatext_friend = "Friends position (0 for disabled)"
TukuiL.option_datatext_time = "Time position (0 for disabled)"
TukuiL.option_datatext_gold = "Gold position (0 for disabled)"
TukuiL.option_datatext_dps = "Damage per second position (0 for disabled)"
TukuiL.option_datatext_crit = "Crit % position (0 for disabled)"
TukuiL.option_datatext_dur = "Durability position (0 for disabled)"
TukuiL.option_datatext_currency = "Currency position (0 for disabled)"
TukuiL.option_datatext_micromenu = "Micro Menu position (0 for disabled)"
TukuiL.option_datatext_hit = "Hit position (0 for disabled)"
TukuiL.option_datatext_mastery = "Mastery position (0 for disabled)"

-- unit frames
TukuiL.option_unitframes_unitframes = "Unit Frames"
TukuiL.option_unitframes_combatfeedback = "Combat Feedback on player and target"
TukuiL.option_unitframes_totalhpmp = "Display total of health/power"
TukuiL.option_unitframes_showperhp = "Show health percent text on health bar"
TukuiL.option_unitframes_playeraggro = "Enable aggro display on yourself"
TukuiL.option_unitframes_smooth = "Enable smooth bar"
TukuiL.option_unitframes_portrait = "Enable portraits on player and target"
TukuiL.option_unitframes_enable = "Enable Tukui Unit Frames"
TukuiL.option_unitframes_enemypower = "Enable Power display on enemy only"
TukuiL.option_unitframes_enemyhostilitycolor = "Color enemy health bar by hostility (for PVP)"
TukuiL.option_unitframes_focus = "Enable Focus target"
TukuiL.option_unitframes_bordercolor = "Set default border color of panels"
TukuiL.option_unitframes_manalow = "Low mana indicator (All mana class)"
TukuiL.option_unitframes_unicolor = "Enable Unique color theme (grey health bar)"
TukuiL.option_unitframes_classbar = "Enable class bar"
TukuiL.option_unitframes_combobar = "Enable combo bar"
TukuiL.option_unitframes_weakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
TukuiL.option_unitframes_altpowerbar = "Enable Alt Power Bar"
TukuiL.option_unitframes_arenaframes = "Enable arena unit frames"

-- raid frames
TukuiL.option_raidframes = "Raid Frames"
TukuiL.option_raidframes_enablerange = "Enable party/raid Range alpha display"
TukuiL.option_raidframes_range = "Alpha on Party/Raid unit out of range"
TukuiL.option_raidframes_gridonly = "Enable Grid only mode for Healer layout"
TukuiL.option_raidframes_symbol = "Show symbols on party/raid"
TukuiL.option_raidframes_aurawatch = "Enable PVE raid Aura Watch (Grid Only)"
TukuiL.option_raidframes_cooldown = "Show cooldown number (Grid Only)"
TukuiL.option_raidframes_hpvertical = "Show health bar vertically for Grid layout"
TukuiL.option_raidframes_raidaggro = "Enable aggro display on party/raid"
TukuiL.option_raidframes_playerparty = "Show yourself in party"
TukuiL.option_raidframes_gridscale = "Grid Scale"
TukuiL.option_raidframes_healcomm = "Enable healcomm"
TukuiL.option_raidframes_maintank = "Enable Main Tank"
TukuiL.option_raidframes_mainassist = "Enable Main Assist"
TukuiL.option_raidframes_role = "Show Role"
TukuiL.option_raidframes_boss = "Enable Boss Unit Frames"
TukuiL.option_raidframes_showperpw = "Show boss power percent"
TukuiL.option_raidframes_maxgroup = "Only show 5 groups in raid (25 mans raid)"

-- castbar
TukuiL.option_castbar = "Castbar"
TukuiL.option_castbar_enable = "Enable cast bar"
TukuiL.option_castbar_latency = "Show cast bar latency"
TukuiL.option_castbar_icon = "Show icons on cast bar"
TukuiL.option_castbar_ufcastbar = "Set castbar on unitframes"
TukuiL.option_castbar_focus = "Enable focus castbar"
TukuiL.option_castbar_boss = "Enable boss castbar"
TukuiL.option_castbar_arena = "Enable arena castbar"
TukuiL.option_castbar_defaultcolor = "Default color"

-- loot
TukuiL.option_loot = "Loot"
TukuiL.option_loot_enableloot = "Enable loot window"
TukuiL.option_loot_autogreed = "Enable auto-greed for green item at max level"
TukuiL.option_loot_enableroll = "Enable item roll window"

-- map
TukuiL.option_map = "Map"
TukuiL.option_map_enable = "Enable Map"
TukuiL.option_map_mlocation = "Enable minimap location"

-- tooltip
TukuiL.option_tooltip = "Tooltip"
TukuiL.option_tooltip_enable = "Enable tooltip"
TukuiL.option_tooltip_hidecombat = "Hide tooltip in combat"
TukuiL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
TukuiL.option_tooltip_hideuf = "Hide tooltip on unit frames"
TukuiL.option_tooltip_cursor = "Enable cursor tooltip"
TukuiL.option_tooltip_showtalent = "Show talent on tooltip"
TukuiL.option_tooltip_talentonlyinparty = "Show talent only in party"
TukuiL.option_tooltip_showitemlvl = "Show item level on tooltip"
TukuiL.option_tooltip_whotargetting = "Display who is targetting the unit that is in your party/raid."

-- reminder
TukuiL.option_reminder = "Aura Warning"
TukuiL.option_reminder_enable = "Enable player aura warning"
TukuiL.option_reminder_sound = "Enable a warning sound for aura warning"
TukuiL.option_reminder_raidbuffreminder = "Enable RaidBuffReminder Bar below minimap"
TukuiL.option_reminder_onlyininstance = "Show RaidBuffReminder only in instance"

-- action bar
TukuiL.option_actionbar = "Action Bars"
TukuiL.option_actionbar_hidess = "Hide Shapeshift bar or Totem bar"
TukuiL.option_actionbar_showgrid = "Always show Grid on action bar"
TukuiL.option_actionbar_enable = "Enable Tukui action bar"
TukuiL.option_actionbar_hk = "Show hotkey on buttons"
TukuiL.option_actionbar_bt = "Show button name"
TukuiL.option_actionbar_buttonsize = "Size of the main action buttons"
TukuiL.option_actionbar_buttonspacing = "Spacing of the main action buttons"
TukuiL.option_actionbar_petbuttonsize = "Size of pet/shapeshift buttons"

-- pvp
TukuiL.option_pvp = "Pvp"
TukuiL.option_pvp_ii = "Enable Interrupt Icons"

-- cooldowns
TukuiL.option_cooldown = "Cooldowns"
TukuiL.option_cooldown_enable = "Enable cooldown number on buttons"
TukuiL.option_cooldown_th = "Turn cooldown number red at X value"

-- chat
TukuiL.option_chat = "Social"
TukuiL.option_chat_enable = "Enable Tukui Chat"
TukuiL.option_chat_whispersound = "Play sound when receiving private message"
TukuiL.option_chat_background = "Enable chat panel background"
TukuiL.option_chat_justify = "Align right chat"
TukuiL.option_chat_height = "Chat height"
TukuiL.option_chat_rightchat = "Enable right chat"
TukuiL.option_chat_bubbles = "Enable bubble skin"

-- buff
TukuiL.option_auras = "Auras"
TukuiL.option_auras_player = "Enable Tukui Buff/Debuff Frames"
TukuiL.option_auras_auratimer = "Enable timer on auras"
TukuiL.option_auras_aurascale = "Aura text scale on auras"
TukuiL.option_auras_playeraura = "Enable an alternative aura mode for player"
TukuiL.option_auras_targetaura = "Enable target auras"
TukuiL.option_auras_focusdebuff = "Enable focus debuffs"
TukuiL.option_auras_bossdebuff = "Enable boss debuffs"
TukuiL.option_auras_arenadebuff = "Enable arena debuffs"
TukuiL.option_auras_buffrows = "Number of buff rows"
TukuiL.option_auras_debuffrows = "Number of debuff rows"
TukuiL.option_auras_debuffnums = "Number of focus, arena and boss debuffs"
TukuiL.option_auras_totdebuffs = "Enable Target of Target debuffs (High Reso)"
TukuiL.option_auras_onlyselfdebuffs = "Display only our debuffs on target"

-- panels
TukuiL.option_panels = "Panels"
TukuiL.option_panels_infowidth = "Info frame width"
TukuiL.option_panels_bottompanel = "Enable Bottombar"
TukuiL.option_panels_toppanel = "Enable Topbar"
TukuiL.option_panels_location = "Enable location panel"

-- misc
TukuiL.option_misc = "Misc"
TukuiL.option_misc_autoinvite = "Enable Auto-Invite (Friends and Guildmates)"
TukuiL.option_misc_autocustomlagtolerance = "Automatically update the Blizzard Custom Lag Tolerance option to your latency."
TukuiL.option_misc_altpowerbar = "Enable altpowerbar on infoleft"
TukuiL.option_misc_threatbar = "Enable threatbar on inforight"
TukuiL.option_misc_errorenable = "Hide spamming error in the middle of your screen"

-- buttons
TukuiL.option_button_reset = "Reset"
TukuiL.option_button_load = "Apply Settings"
TukuiL.option_button_close = "Close"
TukuiL.option_button_color = "Set Color"
TukuiL.option_setsavedsetttings = "Set settings Per-Character"
TukuiL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
TukuiL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
TukuiL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
TukuiL.option_makeselection = "You must make a selection before you can continue to config."